name: Deploy Spring Boot App to Docker Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to server
        run: |
          rsync -avz --delete ./micro-product ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/micro-product

      - name: Build and run Docker on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USER }}/micro-product/docker
            docker stop micro-product || true && docker rm micro-product || true
            docker build -t micro-product .
            docker run -d -p 8080:8080 --name micro-product micro-product
          EOF